services:
  rabbitmq:
    image: rabbitmq:3.11.7-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672" # Web管理UIを開発用に開放
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PW}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - app-net

#   db:
#     image: mysql:8
#     container_name: db
#     restart: always
#     environment:
#       - MYSQL_ROOT_PASSWORD: ${DB_ROOT_PW}
#       - MYSQL_DATABASE: ${DB_NAME}
#       - MYSQL_USER: ${DB_USER}
#       - MYSQL_PASSWORD: ${DB_PW}
#     ports:
#       - "3306:3306"
#     volumes:
#       - mysql_data:/var/lib/mysql
#     networks:
#       - app-net

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    tty: true
    volumes:
      - ./backend:/usr/src/app
    environment:
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PW=${RABBITMQ_PW}
    networks:
      - app-net

  nfc_service:
    build: ./nfc_service
    container_name: nfc_service
    depends_on:
      - rabbitmq
    tty: true
    volumes:
      - ./nfc_service:/usr/src/app
    environment:
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PW=${RABBITMQ_PW}
    networks:
      - app-net
    devices:
      - "/dev/bus/usb:/dev/bus/usb"
    cap_add:
      - SYS_RAWIO
      - SYS_ADMIN
      
  barcode_service:
    build: ./barcode_service
    container_name: barcode_service
    depends_on:
      - rabbitmq
    tty: true
    volumes:
      - ./barcode_service:/usr/src/app
    environment:
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PW=${RABBITMQ_PW}
    networks:
      - app-net
    # privileged: true
    devices:
      - "/dev/bus/usb:/dev/bus/usb"
    cap_add:
      - SYS_RAWIO
      - SYS_ADMIN

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    tty: true
    volumes:
      - ./frontend:/usr/src/app
    environment:
      - REACT_APP_API_URL=http://backend:5000
    networks:
      - app-net


  # # phpMyAdmin
  # # DB管理用コンテナ
  # # http://localhost:8081でDBのWebUIにアクセス
  # phpmyadmin:
  #   container_name: phpmyadmin
  #   image: phpmyadmin/phpmyadmin
  #   depends_on:
  #     - db
  #   environment:
  #     - PMA_ARBITRARY: 1
  #     - PMA_HOSTS: ${DB_HOST}
  #     - PMA_USER: root
  #     - PMA_PASSWORD: ${DB_ROOT_PW}
  #   ports:
  #     - 8080:80
  #   networks:
  #     - app-net

volumes:
    rabbitmq_data:  # RabbitMQのデータを永続化
#     mysql_data: #MYSQLのデータを永続化

networks:
  app-net:
    driver: bridge